server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.37.177.117:3306/rasp?characterEncoding=utf-8&useSSL=false
    username: root
    password: jvm@s4ndbox@rAsp